modLoader="javafml"
loaderVersion="[43,)"
license="MIT"
issueTrackerURL="https://github.com/MattDahEpic/EnderdragonSkull/issues"

[[mods]]
    modId="enderdragonskull"
    version="${file.jarVersion}"
    displayName="Enderdragon Skull"
    updateJSONURL="https://raw.githubusercontent.com/MattDahEpic/Version/master/enderdragonskull.json"
    displayURL="http://minecraft.curseforge.com/projects/enderdragon-skull"
    credits="Thanks to the entire open source mod community from which I used code."
    authors="MattDahEpic"
    description='''
    Makes the enderdragon drop an skull.
    '''

    [[dependencies.enderdragonskull]]
        modId="forge"
        mandatory=true
        versionRange="[43,)"
        ordering="NONE"
        side="BOTH"
    [[dependencies.enderdragonskull]]
        modId="minecraft"
        mandatory=true
        versionRange="[1.19.2,)"
        ordering="NONE"
        side="BOTH"
